/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 헬스체크. 부팅 검증 및 외부 모니터링용.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description 상품설명서·약관 → 타겟 페르소나 + 반응도 + 페르소나별 의견 + 리포트.
         */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Text
         * @description 파일을 받아 텍스트만 추출해 반환.
         *
         *     프론트엔드는 응답의 `text`를 textarea에 채우고, 사용자는 그대로 분석 가능.
         */
        post: operations["extract_text_api_extract_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract-text/supported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Supported Formats
         * @description 지원 형식 목록 (UI에서 accept 속성 채울 때 사용).
         */
        get: operations["supported_formats_api_extract_text_supported_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Endpoint
         * @description 분석 이력 요약 리스트 (최신순).
         */
        get: operations["list_endpoint_api_analyses_get"];
        put?: never;
        post?: never;
        /**
         * Delete All Endpoint
         * @description 모든 분석 + 시뮬레이션 일괄 삭제 (되돌릴 수 없음).
         */
        delete: operations["delete_all_endpoint_api_analyses_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Endpoint
         * @description 분석 이력 단건 전체 (4섹션 다시 렌더링용).
         *
         *     응답은 AnalyzeResponse와 동일 구조 + 추가 메타(id, created_at, product_text 일부)
         *     + simulations(이 분석에 묶인 과거 시뮬레이션 전체, 최신순).
         */
        get: operations["detail_endpoint_api_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Endpoint
         * @description 분석 단건 + 연관 시뮬레이션 삭제.
         */
        delete: operations["delete_endpoint_api_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description 기 분석된 페르소나 상위 N명에게 주관식 문항 응답 시뮬레이션.
         */
        post: operations["simulate_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description 데이터셋 전체 통계 — 메타 + 인구통계 분포 + 지역 + 직업 Top + 페르소나 길이.
         *
         *     PersonaStore의 df를 활용하므로 임베딩과 무관하게 즉시 응답.
         *     내부적으로 lru_cache로 1회만 계산 (~수십 ms 이내).
         */
        get: operations["overview_api_dataset_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/personas/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Persona Samples
         * @description 특정 페르소나 카테고리에서 대표 샘플 N건 (길이 양극단).
         *
         *     /overview 페이지의 "페르소나 텍스트 길이" 표에서 카테고리 클릭 시 사용.
         */
        get: operations["persona_samples_api_dataset_personas_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/personas/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Persona Search
         * @description 자연어 시멘틱 검색 (메타 추출 + 임베딩 정렬 하이브리드).
         *
         *     내부적으로 /personas/filter와 동일한 메타 추출 → 후보 축소 → 잔여 의미 임베딩 정렬
         *     파이프라인을 사용. 응답에는 추출된 메타(extracted_filter)와 단계별 매칭 수
         *     (meta_filter_total / match_total)가 포함된다.
         *
         *     예: "은퇴 후 등산 좋아하는 60대 남성" → sex=남자, age 60+, employment=unemployed,
         *         remaining='등산' → 메타 후보 N명, 임베딩 ≥0.3 컷으로 M명 매칭.
         *     예: "30대 워킹맘 수도권" → sex=여자, age 30-39, has_children=true, employment=employed,
         *         provinces=[서울/경기/인천], remaining='' → 메타 후보가 곧 매칭 결과.
         */
        post: operations["persona_search_api_dataset_personas_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/personas/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Personas Facets
         * @description 필터 UI에 채울 distinct 값 목록 (province / family_type / education_level 등).
         *
         *     1회 계산 후 lru_cache (df 불변 가정). 응답 크기 작음.
         */
        get: operations["personas_facets_api_dataset_personas_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/personas/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Personas Filter
         * @description 메타 필터 + (옵션) 자연어 검색 + 페이지네이션 + 분포 통계.
         *
         *     흐름:
         *       1) store.filter_indices(meta) → 후보 인덱스
         *       2) req.query 있으면 → 임베딩 후 그 인덱스 대상 cosine 정렬, similarity 부여
         *                    없으면 → 인덱스 그대로 (정렬은 uuid asc로 안정)
         *       3) 페이지 슬라이스 + 인구통계 분포(sex/age_bins/province) 집계
         */
        post: operations["personas_filter_api_dataset_personas_filter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/personas/{persona_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Persona Detail
         * @description 단일 페르소나 상세 — PersonaDetailModal용 풀 프로필.
         */
        get: operations["get_persona_detail_api_dataset_personas__persona_uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Surveys Endpoint */
        get: operations["list_surveys_endpoint_api_surveys_get"];
        put?: never;
        /** Create Survey */
        post: operations["create_survey_api_surveys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{survey_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Survey Endpoint */
        get: operations["get_survey_endpoint_api_surveys__survey_id__get"];
        /** Update Survey Endpoint */
        put: operations["update_survey_endpoint_api_surveys__survey_id__put"];
        post?: never;
        /** Delete Survey Endpoint */
        delete: operations["delete_survey_endpoint_api_surveys__survey_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/suggest-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Questions
         * @description 제목·목적·대상자를 바탕으로 AI가 질문 N개를 추천.
         *
         *     호출 시점: 마법사 Step 3에서 "AI 추천" 버튼.
         *     출력: SurveyQuestion[] (id·order 자동 할당, validate 통과 보장).
         */
        post: operations["suggest_questions_api_surveys_suggest_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/questions/parse-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse File */
        post: operations["parse_file_api_surveys_questions_parse_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/questions/template/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template Excel */
        get: operations["template_excel_api_surveys_questions_template_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/questions/template/word": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template Word */
        get: operations["template_word_api_surveys_questions_template_word_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{survey_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Run
         * @description 설문 시뮬레이션 시작 (백그라운드).
         *
         *     Args:
         *         force: True이면 status='running'이라도 강제로 다시 시작.
         *                pm2 재시작 등으로 백그라운드 작업이 끊겨 세션이 stale running으로 남았을 때 복구용.
         *                completed 세션은 보존(캐시 hit으로 즉시 통과), running/failed 세션은 pending으로 리셋.
         *
         *     Returns:
         *         {status: "started", survey_id, total, reset, completed_preserved}
         */
        post: operations["trigger_run_api_surveys__survey_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{survey_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Survey Status
         * @description 진행률·통계 집계. polling으로 자주 호출되니 IO 최소화.
         */
        get: operations["survey_status_api_surveys__survey_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{survey_id}/retry-failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Failed
         * @description failed 상태 세션만 다시 실행. completed는 캐시 hit으로 즉시 통과.
         */
        post: operations["retry_failed_api_surveys__survey_id__retry_failed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{survey_id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Responses */
        get: operations["get_responses_api_surveys__survey_id__responses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{survey_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description 완료된 응답 전체 집계. 백엔드에서 사전 가공해 프론트 부담 제거.
         */
        get: operations["get_report_api_surveys__survey_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{survey_id}/commentary/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Commentary
         * @description 비동기 백필. 즉시 202 반환 후 background에서 LLM 호출 + 저장.
         */
        post: operations["regenerate_commentary_api_surveys__survey_id__commentary_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{survey_id}/report.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Csv
         * @description 응답 raw 데이터 CSV — 1행 = 페르소나 1명.
         */
        get: operations["get_report_csv_api_surveys__survey_id__report_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Segments Endpoint */
        get: operations["list_segments_endpoint_api_segments_get"];
        put?: never;
        /** Create Segment */
        post: operations["create_segment_api_segments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Segment Endpoint */
        get: operations["get_segment_endpoint_api_segments__segment_id__get"];
        put?: never;
        post?: never;
        /** Delete Segment Endpoint */
        delete: operations["delete_segment_endpoint_api_segments__segment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysesListResponse */
        AnalysesListResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["AnalysisSummary"][];
        };
        /** AnalysisSummary */
        AnalysisSummary: {
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
            /** Summary */
            summary: string;
            /** Key Benefits */
            key_benefits: string[];
            /** Max Score */
            max_score: number;
            /** Top Persona Count */
            top_persona_count: number;
            /** Top Province */
            top_province?: string | null;
            /**
             * Top Province Count
             * @default 0
             */
            top_province_count: number;
            /** Total Ms */
            total_ms: number;
            /**
             * Simulation Count
             * @default 0
             */
            simulation_count: number;
        };
        /**
         * AnalyzeRequest
         * @description POST /api/analyze 요청 바디.
         */
        AnalyzeRequest: {
            /**
             * Product Text
             * @description 상품설명서 + 약관 본문 (20-20000자)
             */
            product_text: string;
            /**
             * Top K
             * @description 반환할 상위 페르소나 수
             * @default 100
             */
            top_k: number;
            /**
             * Llm Provider
             * @description 사용할 LLM provider. anthropic=Claude Sonnet+Haiku, sllm=OpenAI 호환 vLLM (Qwen3.6-27B-FP8)
             * @default sllm
             * @enum {string}
             */
            llm_provider: "anthropic" | "sllm";
        };
        /**
         * AnalyzeResponse
         * @description POST /api/analyze 응답.
         */
        AnalyzeResponse: {
            /** Analysis Id */
            analysis_id: string;
            selling_points: components["schemas"]["SellingPoints"];
            /** Top Personas */
            top_personas: components["schemas"]["PersonaHit"][];
            /**
             * Bottom Personas
             * @description 전체 점수 하위 N명 (반대 반응 비교용)
             */
            bottom_personas?: components["schemas"]["PersonaHit"][];
            /**
             * Province Stats
             * @description 상위 50명 기준 시도 집계 (카드용)
             */
            province_stats: components["schemas"]["RegionStat"][];
            /**
             * District Stats
             * @description 상위 시도의 시군구 집계 (drill-down용)
             */
            district_stats: components["schemas"]["RegionStat"][];
            /** @description 100만 행 전체 스코어링 기반 모집단 통계 */
            population_stats: components["schemas"]["PopulationStats"];
            /**
             * Top Opinions
             * @description top_personas와 같은 순서로 매칭된 의견 (uuid join도 가능)
             */
            top_opinions?: components["schemas"]["PersonaOpinion"][];
            /**
             * Bottom Opinions
             * @description bottom_personas와 같은 순서로 매칭된 의견
             */
            bottom_opinions?: components["schemas"]["PersonaOpinion"][];
            /**
             * Report Md
             * @description Claude(Haiku) 생성 FP/기획자용 마크다운 리포트
             */
            report_md: string;
            /**
             * Elapsed Ms
             * @description 단계별 소요 ms: selling_points, embed, score, opinions, report
             */
            elapsed_ms: {
                [key: string]: number;
            };
        };
        /**
         * Answer
         * @description 단일 페르소나 × 단일 질문의 응답.
         */
        Answer: {
            /** Question Id */
            question_id: string;
            /** Answer Value */
            answer_value: string | number | string[];
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /** Body_extract_text_api_extract_text_post */
        Body_extract_text_api_extract_text_post: {
            /** File */
            file: string;
        };
        /** Body_parse_file_api_surveys_questions_parse_file_post */
        Body_parse_file_api_surveys_questions_parse_file_post: {
            /** File */
            file: string;
        };
        /**
         * CohortStat
         * @description percentile 기반 cohort 1개.
         */
        CohortStat: {
            /**
             * Name
             * @description cohort 식별자 (core/target/interest)
             */
            name: string;
            /**
             * Label
             * @description 표시용 라벨 (예: '핵심 타겟')
             */
            label: string;
            /**
             * Percentile
             * @description 상위 X% (0~100)
             */
            percentile: number;
            /**
             * Size
             * @description 해당 cohort 인원 수
             */
            size: number;
            /**
             * Min Score
             * @description 이 cohort에 포함되는 최소 점수
             */
            min_score: number;
            /**
             * Avg Score
             * @description 평균 점수
             */
            avg_score: number;
        };
        /**
         * DemographicGroup
         * @description Nemotron 인구통계 1개 컬럼의 분포.
         *
         *     자유 텍스트 컬럼(persona, *_persona, skills_and_expertise,
         *     hobbies_and_interests, career_goals_and_ambitions)은 카테고리 분포로
         *     표현할 수 없어 포함하지 않는다.
         */
        DemographicGroup: {
            /**
             * Column
             * @description 원본 컬럼명 (예: sex, marital_status)
             */
            column: string;
            /**
             * Label
             * @description 표시용 라벨 (예: 성별, 혼인 상태)
             */
            label: string;
            /**
             * Bins
             * @description 분포 막대 (내림차순)
             */
            bins: components["schemas"]["DistributionBin"][];
            /**
             * Total Unique
             * @description 해당 컬럼의 전체 고유값 수
             */
            total_unique: number;
            /**
             * Truncated To
             * @description Top N으로 잘랐다면 N, 아니면 None (즉 bins가 전체)
             */
            truncated_to?: number | null;
        };
        /**
         * DistributionBin
         * @description 히스토그램 / 카테고리 분포 1개 막대.
         */
        DistributionBin: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /**
         * ExecutionConfig
         * @description LLM 실행 파라미터.
         */
        ExecutionConfig: {
            /**
             * Llm Provider
             * @default anthropic
             * @enum {string}
             */
            llm_provider: "anthropic" | "sllm";
            /**
             * Model
             * @default claude-haiku-4-5
             */
            model: string;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Include Reasoning
             * @default true
             */
            include_reasoning: boolean;
        };
        /** ExtractResponse */
        ExtractResponse: {
            /** Filename */
            filename: string;
            /** Char Count */
            char_count: number;
            /** Text */
            text: string;
            /** Truncated */
            truncated: boolean;
        };
        /**
         * ExtractedFilter
         * @description 자연어 쿼리에서 LLM이 추출한 메타 조건. 사용자에게 투명하게 노출.
         */
        ExtractedFilter: {
            /** Sex */
            sex?: string[];
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Provinces */
            provinces?: string[];
            /** Marital Statuses */
            marital_statuses?: string[];
            /** Has Children */
            has_children?: boolean | null;
            /** Employment Status */
            employment_status?: string | null;
            /** Occupations */
            occupations?: string[];
            /** Education Levels */
            education_levels?: string[];
            /** Family Types */
            family_types?: string[];
            /** Additional Filters */
            additional_filters?: {
                [key: string]: string[];
            };
            /**
             * Remaining Query
             * @default
             */
            remaining_query: string;
        };
        /** FailedPersonaInfo */
        FailedPersonaInfo: {
            /** Persona Uuid */
            persona_uuid: string;
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OpenEndedSample */
        OpenEndedSample: {
            /** Persona Uuid */
            persona_uuid: string;
            /** Sex */
            sex: string;
            /** Age */
            age: number;
            /** Province */
            province: string;
            /** Occupation */
            occupation: string;
            /** Answer */
            answer: string;
            /** Reasoning */
            reasoning: string;
            /** Confidence */
            confidence: number;
        };
        /** ParseResult */
        ParseResult: {
            /** Filename */
            filename: string;
            /**
             * File Format
             * @enum {string}
             */
            file_format: "xlsx" | "csv" | "docx";
            summary: components["schemas"]["ParseSummary"];
            /** Questions */
            questions: components["schemas"]["ParsedQuestion"][];
        };
        /** ParseSummary */
        ParseSummary: {
            /** Total */
            total: number;
            /** Valid */
            valid: number;
            /** Invalid */
            invalid: number;
        };
        /** ParsedQuestion */
        ParsedQuestion: {
            /** Row */
            row: number;
            /**
             * Type
             * @enum {string}
             */
            type: "single_choice" | "multi_choice" | "scale" | "open_ended" | "nps";
            /**
             * Text
             * @default
             */
            text: string;
            /** Options */
            options?: string[];
            /** Scale Min */
            scale_min?: number | null;
            /** Scale Max */
            scale_max?: number | null;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Errors */
            errors?: string[];
        };
        /** PersonaCard */
        PersonaCard: {
            /** Uuid */
            uuid: string;
            /** Sex */
            sex: string;
            /** Age */
            age: number;
            /** Province */
            province: string;
            /** District */
            district: string;
            /** Occupation */
            occupation: string;
            /** Family Type */
            family_type: string | null;
            /** Marital Status */
            marital_status: string | null;
            /** Education Level */
            education_level: string | null;
            /** Persona */
            persona: string;
            /** Similarity */
            similarity?: number | null;
        };
        /** PersonaFilterDistribution */
        PersonaFilterDistribution: {
            /** Sex */
            sex: {
                [key: string]: number;
            };
            /** Age Bins */
            age_bins: {
                [key: string]: unknown;
            }[];
            /** Province */
            province: {
                [key: string]: number;
            };
        };
        /**
         * PersonaFilterRequest
         * @description 페르소나 메타 필터 + 옵션 자연어 검색.
         *
         *     빈 필드는 해당 조건 무시. query가 있으면 후보 인덱스 대상 cosine 정렬.
         */
        PersonaFilterRequest: {
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Sex */
            sex?: ("남자" | "여자")[];
            /** Provinces */
            provinces?: string[];
            /** Family Types */
            family_types?: string[];
            /** Education Levels */
            education_levels?: string[];
            /** Occupations */
            occupations?: string[];
            /** Query */
            query?: string | null;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 24
             */
            page_size: number;
        };
        /** PersonaFilterResponse */
        PersonaFilterResponse: {
            /** Total */
            total: number;
            /** Meta Filter Total */
            meta_filter_total: number;
            /** Match Threshold */
            match_threshold: number | null;
            extracted_filter: components["schemas"]["ExtractedFilter"] | null;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Page Personas */
            page_personas: components["schemas"]["PersonaCard"][];
            distribution: components["schemas"]["PersonaFilterDistribution"];
            /** Has Query */
            has_query: boolean;
            /** Elapsed Ms */
            elapsed_ms: {
                [key: string]: number;
            };
        };
        /**
         * PersonaHit
         * @description 매칭된 페르소나 1명 (상위/하위 모두 동일 스키마).
         */
        PersonaHit: {
            /** Uuid */
            uuid: string;
            /**
             * Score
             * @description 0-100 정규화 반응도 점수
             */
            score: number;
            /** Persona */
            persona: string;
            /** Province */
            province: string;
            /** District */
            district: string;
            /** Sex */
            sex: string;
            /** Age */
            age: number;
            /** Occupation */
            occupation: string;
            /** Education Level */
            education_level?: string | null;
            /** Family Type */
            family_type?: string | null;
            /** Marital Status */
            marital_status?: string | null;
            /** Military Status */
            military_status?: string | null;
        };
        /**
         * PersonaOpinion
         * @description 페르소나가 상품에 대해 빙의 작성한 의견.
         *
         *     설문(simulation)이 임의의 질문에 대한 응답이라면, opinion은
         *     상품 자체에 대한 자유 코멘트. 분석 시점에 top_k + bottom_k 모두 생성.
         */
        PersonaOpinion: {
            /** Persona Uuid */
            persona_uuid: string;
            /**
             * Opinion Text
             * @description 1-2문장 본인 말투 의견
             */
            opinion_text: string;
            /**
             * Sentiment
             * @enum {string}
             */
            sentiment: "긍정" | "중립" | "부정";
            /**
             * Purchase Intent
             * @description 가입 의향 1-5
             */
            purchase_intent: number;
            /**
             * Key Concern
             * @description 본인이 가장 신경 쓰는 한 가지 (없으면 None)
             */
            key_concern?: string | null;
        };
        /**
         * PersonaResponse
         * @description 페르소나 1명의 시뮬레이션 응답.
         */
        PersonaResponse: {
            /** Persona Uuid */
            persona_uuid: string;
            /**
             * Persona Summary
             * @description 식별용 한 줄 요약 (예: "남자 45세 · 경기 수원 · 회사원")
             */
            persona_summary: string;
            /**
             * Response Text
             * @description 페르소나가 자기 말투로 작성한 응답 본문
             */
            response_text: string;
            /**
             * Sentiment
             * @enum {string}
             */
            sentiment: "긍정" | "중립" | "부정";
            /**
             * Purchase Intent
             * @description 가입 의향 1-5
             */
            purchase_intent: number;
            /**
             * Key Concern
             * @description 주요 우려·관심사 한 줄 (없으면 None)
             */
            key_concern?: string | null;
        };
        /** PersonaSearchRequest */
        PersonaSearchRequest: {
            /**
             * Query
             * @description 자연어 검색 쿼리
             */
            query: string;
            /**
             * Limit
             * @description 반환할 페르소나 수
             * @default 20
             */
            limit: number;
        };
        /** PersonaWithSession */
        PersonaWithSession: {
            /** Persona Uuid */
            persona_uuid: string;
            /** Sex */
            sex: string;
            /** Age */
            age: number;
            /** Province */
            province: string;
            /** District */
            district: string;
            /** Occupation */
            occupation: string;
            /** Family Type */
            family_type: string | null;
            /** Marital Status */
            marital_status: string | null;
            /** Persona */
            persona: string;
            session: components["schemas"]["ResponseSession"];
        };
        /**
         * PopulationStats
         * @description 100만 행 전체 스코어링 결과 + 모집단 통계.
         *
         *     cohort 정의:
         *       - core: 상위 0.5% (≈5,000명) — 카드·리포트 컨텍스트로 이미 노출됨
         *       - target: 상위 5% (≈50,000명) — demographics 집계의 주 모집단
         *       - interest: 상위 20% (≈200,000명) — 점수 분포 차트 베이스
         */
        PopulationStats: {
            /**
             * Total Scored
             * @description 전체 스코어링된 페르소나 수
             */
            total_scored: number;
            /**
             * Cohorts
             * @description 3단계 cohort 정보
             */
            cohorts: components["schemas"]["CohortStat"][];
            /**
             * Score Distribution
             * @description 5점 단위 점수 히스토그램 (interest cohort 기준)
             */
            score_distribution: components["schemas"]["DistributionBin"][];
            /**
             * Demographics
             * @description Nemotron 카테고리형 컬럼별 분포 (target cohort 기준). 표시 우선순위 순서대로.
             */
            demographics: components["schemas"]["DemographicGroup"][];
            /**
             * Districts Full
             * @description 타겟 cohort(상위 5%, ≈5만명) 기준 전국 시군구별 집계. name 형식: '시도-시군구' (예: '경기-광명시'). 지도 choropleth와 Top N 표용. count 내림차순.
             */
            districts_full?: components["schemas"]["RegionStat"][];
        };
        /**
         * Question
         * @description 설문 1문항.
         *
         *     유형별 필드 사용:
         *       - single_choice / multi_choice: options 필수 (최소 2개)
         *       - scale: scale_min/scale_max 필수 (예: 1-5, 1-7)
         *       - open_ended: 추가 필드 없음
         *       - nps: scale_min=0, scale_max=10 고정
         */
        Question: {
            /**
             * Id
             * @description uuid4
             */
            id: string;
            /**
             * Order
             * @description 1-based 노출 순서
             */
            order: number;
            /**
             * Type
             * @enum {string}
             */
            type: "single_choice" | "multi_choice" | "scale" | "open_ended" | "nps";
            /** Text */
            text: string;
            /** Options */
            options?: string[];
            /** Scale Min */
            scale_min?: number | null;
            /** Scale Max */
            scale_max?: number | null;
            /** Scale Label Low */
            scale_label_low?: string | null;
            /** Scale Label High */
            scale_label_high?: string | null;
            /**
             * Required
             * @default true
             */
            required: boolean;
        };
        /** QuestionReport */
        QuestionReport: {
            /** Question Id */
            question_id: string;
            /** Order */
            order: number;
            /**
             * Type
             * @enum {string}
             */
            type: "single_choice" | "multi_choice" | "scale" | "open_ended" | "nps";
            /** Text */
            text: string;
            /** Total Responses */
            total_responses: number;
            /** Avg Confidence */
            avg_confidence: number;
            /** Choice Distribution */
            choice_distribution?: {
                [key: string]: number;
            } | null;
            /** Scale Histogram */
            scale_histogram?: {
                [key: string]: unknown;
            }[] | null;
            /** Scale Mean */
            scale_mean?: number | null;
            /** Scale Median */
            scale_median?: number | null;
            /** Open Ended Samples */
            open_ended_samples?: components["schemas"]["OpenEndedSample"][] | null;
            /** Open Ended Length Avg */
            open_ended_length_avg?: number | null;
            /** Open Ended Length Max */
            open_ended_length_max?: number | null;
        };
        /**
         * RegionStat
         * @description 시도/시군구별 집계 통계.
         */
        RegionStat: {
            /**
             * Name
             * @description province 또는 district 이름
             */
            name: string;
            /**
             * Count
             * @description 해당 지역에 속한 상위 페르소나 수
             */
            count: number;
            /**
             * Avg Score
             * @description 해당 지역 평균 반응도
             */
            avg_score: number;
            /** Top Persona Uuid */
            top_persona_uuid?: string | null;
        };
        /** ReportResponse */
        ReportResponse: {
            survey: components["schemas"]["Survey"];
            summary: components["schemas"]["ReportSummary"];
            respondent_distribution: components["schemas"]["RespondentDistribution"];
            /** Questions */
            questions: components["schemas"]["QuestionReport"][];
            /** Overall Commentary */
            overall_commentary?: string | null;
        };
        /** ReportSummary */
        ReportSummary: {
            /** Total Completed */
            total_completed: number;
            /** Total Failed */
            total_failed: number;
            /** Total Tokens */
            total_tokens: number;
            /** Avg Response Seconds */
            avg_response_seconds: number | null;
        };
        /** RespondentDistribution */
        RespondentDistribution: {
            /** Sex */
            sex: {
                [key: string]: number;
            };
            /** Age Bins */
            age_bins: {
                [key: string]: unknown;
            }[];
            /** Province */
            province: {
                [key: string]: number;
            };
        };
        /**
         * ResponseSession
         * @description 단일 페르소나의 설문 응답 세션.
         */
        ResponseSession: {
            /**
             * Id
             * @description {survey_id}:{persona_uuid} 합성
             */
            id: string;
            /** Survey Id */
            survey_id: string;
            /** Persona Uuid */
            persona_uuid: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Llm Model Used
             * @default
             */
            llm_model_used: string;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /** Error */
            error?: string | null;
            /** Answers */
            answers?: components["schemas"]["Answer"][];
        };
        /** ResponsesResponse */
        ResponsesResponse: {
            /** Survey Id */
            survey_id: string;
            /** Total Personas */
            total_personas: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Items */
            items: components["schemas"]["PersonaWithSession"][];
        };
        /** RetryResponse */
        RetryResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "noop";
            /** Survey Id */
            survey_id: string;
            /** Retry Count */
            retry_count: number;
        };
        /**
         * Segment
         * @description 저장된 페르소나 세그먼트. 마법사 Step 2에서 불러옴.
         */
        Segment: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            filter: components["schemas"]["TargetFilter"];
            /** Persona Uuids */
            persona_uuids: string[];
            /**
             * Size
             * @default 0
             */
            size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SegmentCreateRequest */
        SegmentCreateRequest: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            filter: components["schemas"]["TargetFilter"];
            /** Persona Uuids */
            persona_uuids: string[];
        };
        /** SegmentListResponse */
        SegmentListResponse: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * SellingPoints
         * @description Claude(Sonnet)가 상품 텍스트에서 추출한 분석 결과.
         *
         *     tool_use 모드로 스키마 강제. 누락 가능 필드는 None/빈 배열로.
         */
        SellingPoints: {
            /**
             * Summary
             * @description 상품을 한 줄로 요약
             */
            summary: string;
            /**
             * Key Benefits
             * @description 핵심 혜택 3-5개
             */
            key_benefits?: string[];
            /**
             * Target Age Min
             * @description 최소 가입 연령 (없으면 None)
             */
            target_age_min?: number | null;
            /**
             * Target Age Max
             * @description 최대 가입 연령 (없으면 None)
             */
            target_age_max?: number | null;
            /**
             * Target Sex
             * @description ["남자"] / ["여자"] / [] (성별 무관)
             */
            target_sex?: string[];
            /**
             * Target Family Types
             * @description 우대되는 가구 유형 (예: '배우자·자녀와 거주')
             */
            target_family_types?: string[];
            /**
             * Target Education Levels
             * @description 필요·우대되는 교육 수준 (enum 7값): '무학', '초등학교', '중학교', '고등학교', '2~3년제 전문대학', '4년제 대학교', '대학원'
             */
            target_education_levels?: string[];
            /**
             * Target Occupations
             * @description 직업 키워드 (occupation 컬럼에 부분 매칭). 예: ['의사', '교수', '간호사']. 약관에 직업 한정이 없으면 []
             */
            target_occupations?: string[];
            /**
             * Target Keywords
             * @description 페르소나 매칭에 쓸 5-10개 한국어 키워드
             */
            target_keywords?: string[];
            /**
             * Persona Category Weights
             * @description 6개 페르소나 카테고리 가중치 (합=1.0)
             */
            persona_category_weights?: {
                [key: string]: number;
            };
        };
        /** SessionCounts */
        SessionCounts: {
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Completed
             * @default 0
             */
            completed: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
        };
        /**
         * SimulateRequest
         * @description POST /api/simulate 요청 바디.
         */
        SimulateRequest: {
            /**
             * Analysis Id
             * @description 기 분석 ID (top_personas를 재사용)
             */
            analysis_id: string;
            /**
             * Question
             * @description 페르소나에게 던질 주관식 질문 (5-300자)
             */
            question: string;
            /**
             * N Respondents
             * @description 응답자 수 (top_personas 상위 N명)
             * @default 5
             * @enum {integer}
             */
            n_respondents: 3 | 5 | 10;
            /**
             * Llm Provider
             * @description 시뮬레이션에 사용할 LLM provider (anthropic 또는 sllm)
             * @default sllm
             * @enum {string}
             */
            llm_provider: "anthropic" | "sllm";
        };
        /**
         * SimulateResponse
         * @description POST /api/simulate 응답.
         */
        SimulateResponse: {
            /** Simulation Id */
            simulation_id: string;
            /** Analysis Id */
            analysis_id: string;
            /** Question */
            question: string;
            /** Responses */
            responses: components["schemas"]["PersonaResponse"][];
            /**
             * Elapsed Ms
             * @description 단계별 소요 ms: simulate, persist, total
             */
            elapsed_ms: {
                [key: string]: number;
            };
        };
        /** SuggestQuestionsRequest */
        SuggestQuestionsRequest: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Objective
             * @default
             */
            objective: string;
            target_filter?: components["schemas"]["TargetFilter"] | null;
            /**
             * Num
             * @default 5
             */
            num: number;
            /** Existing Question Texts */
            existing_question_texts?: string[];
            /**
             * Start Order
             * @description 첫 추천 질문의 order (기존 질문 다음부터)
             * @default 1
             */
            start_order: number;
        };
        /** SuggestQuestionsResponse */
        SuggestQuestionsResponse: {
            /** Questions */
            questions: components["schemas"]["Question"][];
        };
        /**
         * Survey
         * @description 설문 본체. 마법사 Step 1~4의 결과물.
         */
        Survey: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Objective
             * @description 조사 목적 (LLM 응답 품질 향상에 활용)
             * @default
             */
            objective: string;
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "running" | "completed" | "failed";
            target_filter: components["schemas"]["TargetFilter"];
            execution: components["schemas"]["ExecutionConfig"];
            /** Questions */
            questions?: components["schemas"]["Question"][];
            /**
             * Persona Uuids
             * @description Step 2 확정 시점의 페르소나 스냅샷
             */
            persona_uuids?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SurveyCreateRequest */
        SurveyCreateRequest: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Objective
             * @default
             */
            objective: string;
            target_filter: components["schemas"]["TargetFilter"];
            execution: components["schemas"]["ExecutionConfig"];
            /** Questions */
            questions?: components["schemas"]["Question"][];
            /** Persona Uuids */
            persona_uuids?: string[];
        };
        /** SurveyListResponse */
        SurveyListResponse: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** SurveyStatusResponse */
        SurveyStatusResponse: {
            /** Survey Id */
            survey_id: string;
            /**
             * Survey Status
             * @enum {string}
             */
            survey_status: "draft" | "running" | "completed" | "failed";
            /** Total */
            total: number;
            counts: components["schemas"]["SessionCounts"];
            /** Completed Ratio */
            completed_ratio: number;
            /**
             * Answered Questions
             * @default 0
             */
            answered_questions: number;
            /**
             * Total Planned Answers
             * @default 0
             */
            total_planned_answers: number;
            /**
             * Answered Ratio
             * @default 0
             */
            answered_ratio: number;
            /** Avg Response Seconds */
            avg_response_seconds: number | null;
            /** Total Tokens */
            total_tokens: number;
            /** Failed Personas */
            failed_personas?: components["schemas"]["FailedPersonaInfo"][];
        };
        /**
         * TargetFilter
         * @description 페르소나 선별 조건 — /api/dataset/personas/filter 입력과 호환.
         */
        TargetFilter: {
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Sex */
            sex?: string[];
            /** Provinces */
            provinces?: string[];
            /** Family Types */
            family_types?: string[];
            /** Education Levels */
            education_levels?: string[];
            /** Occupations */
            occupations?: string[];
            /** Query */
            query?: string | null;
            /**
             * Sampling
             * @default random_n
             * @enum {string}
             */
            sampling: "all" | "random_n" | "proportional";
            /**
             * Sample Size
             * @default 100
             */
            sample_size: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean | string;
                    };
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_text_api_extract_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_text_api_extract_text_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    supported_formats_api_extract_text_supported_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_endpoint_api_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_endpoint_api_analyses_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    detail_endpoint_api_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_endpoint_api_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_dataset_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    persona_samples_api_dataset_personas_samples_get: {
        parameters: {
            query?: {
                /** @description 페르소나 카테고리 컬럼. 허용: persona, professional_persona, sports_persona, arts_persona, travel_persona, culinary_persona, family_persona */
                column?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    persona_search_api_dataset_personas_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personas_facets_api_dataset_personas_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    personas_filter_api_dataset_personas_filter_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaFilterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaFilterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_persona_detail_api_dataset_personas__persona_uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_surveys_endpoint_api_surveys_get: {
        parameters: {
            query?: {
                status?: ("draft" | "running" | "completed" | "failed") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_survey_api_surveys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SurveyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Survey"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_survey_endpoint_api_surveys__survey_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Survey"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_survey_endpoint_api_surveys__survey_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SurveyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Survey"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_survey_endpoint_api_surveys__survey_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_questions_api_surveys_suggest_questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestQuestionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestQuestionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_file_api_surveys_questions_parse_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_file_api_surveys_questions_parse_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    template_excel_api_surveys_questions_template_excel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    template_word_api_surveys_questions_template_word_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_run_api_surveys__survey_id__run_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    survey_status_api_surveys__survey_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_failed_api_surveys__survey_id__retry_failed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_responses_api_surveys__survey_id__responses_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                /** @description 페르소나 텍스트 부분 매칭 */
                q?: string | null;
                /** @description 세션 상태 필터: "completed"/"failed"/"pending"/"running" */
                status_filter?: string | null;
            };
            header?: never;
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_surveys__survey_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_commentary_api_surveys__survey_id__commentary_regenerate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_csv_api_surveys__survey_id__report_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                survey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_segments_endpoint_api_segments_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_segment_api_segments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Segment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_endpoint_api_segments__segment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Segment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_segment_endpoint_api_segments__segment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
